### ISSUE TITLE
Eternity causes freeze when trying to learn geo spells

### ISSUE THREAD

**Issue by ReaperX** [giulianoriccio/Lua#24]
When eternity is active, it reproducibly makes FFXI unresponsive when trying to learn a geo spell from a geomantic reservoir. This does not happen when eternity is unloaded.

**Comment by Jammingway** [comment]
I've noted this same issue as well. However, the game itself does not freeze, but it will not let you do anything further beyond camera controls. It seems to be because when learning Geo spells it wants a bit of a delay since there is the opportunity to get free skill ups when timed properly and Enternity simply goes too fast.

Aside from this it's a great addon that works well.

**Comment by giulianoriccio** [comment]
Does it happen if you already have the spell? Asking because otherwise I'll have a limited amount of tries to test it.

**Comment by ReaperX** [comment]
Unfortunately, it doesn't. You just get the message that there is nothing out of the ordinary.

**Comment by giulianoriccio** [comment]
Ok thank you. I'll see what I can do.

**Comment by giulianoriccio** [comment]
It should be fixed now. Let me know if it happens again.
