### ISSUE TITLE
Plasmon Positioning?

### ISSUE THREAD

**Issue by WolfeMasters** [giulianoriccio/Lua#26]
I have been trying to reposition the Plasmon addon and can not figure out how to get the thing to move properly.

//plasmon position [[-h]|[-x <x>] [-y <y>]]

I use this and get nowhere.  Is there a way to get it to show the current location too?  I use other addons for counting timers and this gets in the way.  I want to move it up to the top left of the screen.

I'd also like it if it could not always be on top.  If I open a menu, is there a way to get it to hide (or drop behind menus)?  If not, I'll probably shift it off to the right side of the screen, just above the top of my alliance.

**Comment by giulianoriccio** [comment]
Everything between [ ] means optional, | means "or" while < > defines an input.
So, let's say you wanna move it to 10:400, you should write `//plasmon position -x 10 -y 400`.
The windows are always on top, it's the way windower works since there is no way to put something behind FFXI interface.

ATM there is no way to return the current settings using the console, but I'll think about it for a future update.
